# Generated by Django 4.2.3 on 2023-07-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antibody_app', '0002_abpanel_abspeciesreactivity_antibody_antibodyassay_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZzAntigenReactivity',
        ),
        migrations.DeleteModel(
            name='ZzCloneSpeciesReactivity',
        ),
    ]
