# Generated by Django 4.2.3 on 2023-08-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antibody_app', '0004_panel_delete_abpanel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='panel',
            table='Panel',
        ),
    ]
