# Generated by Django 4.2.3 on 2023-08-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antibody_app', '0005_alter_panel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='panel',
            table='panel',
        ),
    ]
